VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ComprobantesRecibidos"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public Fecha_ As Date
Public Tipo_ As String
Public PuntoDeVenta_ As String
Public NumeroDesde_ As String
Public TipoDocEmisor_ As String
Public NroDocEmisor_ As String
Public DenominacionEmisor_ As String
Public TipoCambio_ As String
Public Moneda_ As String
Public ImpNetoGravado_ As String
Public ImpNetoNoGravado_ As String
Public ImpOpExentas_ As String
Public Iva_ As String
Public ImpTotal_ As String
Public Clave_ As String


