VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "FECAEDetResponse"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public Concepto As String
Public DocTipo As String
Public DocNro As String
Public CbteDesde As String
Public CbteHasta As String
Public CbteFch As String
Public Resultado As String
Public CAE As String
Public CAEFchVto As String

