Attribute VB_Name = "RibbonBarButtonsID"
Option Explicit

Public Enum ID_TAB
    ID_TAB_PANEL_DE_CONTROL = 1
    ID_TAB_VENTAS = 2
    ID_TAB_COMPRAS = 3
    ID_TAB_PLANEAMIENTO = 4
    ID_TAB_DESARROLLO = 5
    ID_TAB_ADMINISTRACION = 6
    ID_TAB_CLIENTES_PROVEEDORES = 7
    ID_TAB_USUARIO = 8
End Enum

Public Enum ID_GROUP
    ID_GROUP_PANEL_DE_CONTROL__USUARIOS_EMPLEADOS = 10
    ID_GROUP_PANEL_DE_CONTROL__CONFIGURAR = 11

    ID_GROUP_VENTAS__COTIZACIONES = 20
    ID_GROUP_VENTAS__PEDIDOS = 21

    ID_GROUP_COMPRAS__REQUERIMIENTOS = 30
    ID_GROUP_COMPRAS__PETICION_OFERTA = 31
    ID_GROUP_COMPRAS__ORDEN_COMPRA = 32
    ID_GROUP_COMPRAS__PRECIOS = 33

    ID_GROUP_PLANEAMIENTO__ORDEN_TRABAJO = 40
    ID_GROUP_PLANEAMIENTO__ORDEN_ENTREGA = 41
    ID_GROUP_PLANEAMIENTO__SEGUIMIENTO = 42
    ID_GROUP_PLANEAMIENTO__REMITOS = 43

    ID_GROUP_DESARROLLO__CENTRO_DE_COSTOS = 50
    ID_GROUP_DESARROLLO__MATERIA_PRIMA = 51
    ID_GROUP_DESARROLLO__MANO_DE_OBRA = 52

    ID_GROUP_ADMINISTRACION__FACTURACION = 60
    ID_GROUP_ADMINISTRACION__COBRANZAS = 61
    ID_GROUP_ADMINISTRACION__CUENTAS_CORRIENTES = 62
    ID_GROUP_ADMINISTRACION__COMPRAS = 63
    ID_GROUP_ADMINISTRACION__VARIOS = 64

    ID_GROUP_ADMINISTRACION__EXTRAS = 73

    ID_GROUP_ADMINISTRACION__CAJAYBANCOS = 65
    ID_GROUP_ADMINISTRACION__LIQUIDACIONES = 66
    ID_GROUP_CLIENTES_PROVEEDORES__CLIENTES = 70
    ID_GROUP_CLIENTES_PROVEEDORES__PROVEEDORES = 71
    ID_GROUP_CLIENTES_PROVEEDORES__AGENDA = 72

    ID_GROUP_USUARIO__HERRAMIENTAS = 80
End Enum

Public Enum ID_BUTTON
    ID_BUTTON_ADD = 90000
    ID_BUTTON_LIST = 90001
    ID_BUTTON_SEARCH = 90003
    ID_BUTTON_NUEVA_PERSONA = 100
    ID_BUTTON_REMITO = 90004
    ID_BUTTON_HISTORICO = 90005
    ID_BUTTON_LISTADO = 90006


    ID_BUTTON_PANEL_DE_CONTROL__USUARIOS_EMPLEADOS__NUEVO_EMPLEADO = 100
    ID_BUTTON_PANEL_DE_CONTROL__USUARIOS_EMPLEADOS__USUARIOS = 101
    ID_BUTTON_PANEL_DE_CONTROL__USUARIOS_EMPLEADOS__EMPLEADOS = 102
    ID_BUTTON_PANEL_DE_CONTROL__USUARIOS_EMPLEADOS__SECTORIZAR = 103
    'ID_BUTTON_PANEL_DE_CONTROL__USUARIOS_EMPLEADOS__SINIESTROS = 104
    'ID_BUTTON_PANEL_DE_CONTROL__USUARIOS_EMPLEADOS__ACCIDENTES = 105
    ID_BUTTON_PANEL_DE_CONTROL__USUARIOS_EMPLEADOS__OS = 14001

    ID_BUTTON_PANEL_DE_CONTROL__CONFIGURAR__SISTEMA = 200
    ID_BUTTON_PANEL_DE_CONTROL__CONFIGURAR__COTIZACIONES = 201
    ID_BUTTON_PANEL_DE_CONTROL__CONFIGURAR__COTIZACIONES__GASTOS = 204
    ID_BUTTON_PANEL_DE_CONTROL__CONFIGURAR__COTIZACIONES__DATOS_VARIOS = 205
    ID_BUTTON_PANEL_DE_CONTROL__CONFIGURAR__TERMINACION = 202
    ID_BUTTON_PANEL_DE_CONTROL__CONFIGURAR__TERMINACION__CONFIG_PINTURA = 206
    ID_BUTTON_PANEL_DE_CONTROL__CONFIGURAR__TERMINACION__DEFINIR_CUENTAS = 207
    ID_BUTTON_PANEL_DE_CONTROL__CONFIGURAR__ADMINISTRACION = 203
    ID_BUTTON_PANEL_DE_CONTROL__CONFIGURAR__ADMINISTRACION__IVA = 208
    ID_BUTTON_PANEL_DE_CONTROL__CONFIGURAR__ADMINISTRACION__FACTURAS = 209
    ID_BUTTON_PANEL_DE_CONTROL__CONFIGURAR__ADMINISTRACION__RETENCIONES = 210
    ID_BUTTON_PANEL_DE_CONTROL__CONFIGURAR__ADMINISTRACION__PERCEPCIONES = 211
    ID_BUTTON_PANEL_DE_CONTROL__CONFIGURAR__LUGARES = 215

    ID_BUTTON_PANEL_DE_CONTROL__VER_ACTUALIZACIONES = 216

    ID_BUTTON_CAJAYBANCOS__CONFIGURAR__ADMINISTRACION__BANCOS = 212
    ID_BUTTON_CAJAYBANCOS__CONFIGURAR__ADMINISTRACION__CUENTAS = 213
    ID_BUTTON_PANEL_DE_CONTROL__CONFIGURAR__DOCUMENTOS = 214
    ID_BUTTON_PANEL_DE_CONTROL__TESTS = 21433

    '------------------------------------------------------------------------------

    ID_BUTTON_VENTAS__COTIZACIONES__NUEVA = 300
    ID_BUTTON_VENTAS__COTIZACIONES__LISTADO = 301
    ID_BUTTON_VENTAS__COTIZACIONES__INFORME = 304
    ID_BUTTON_VENTAS__COTIZACIONES__INFORME_HISTORICO = 302
    ID_BUTTON_VENTAS__COTIZACIONES__INFORME_DINAMICO = 303

    ID_BUTTON_VENTAS__PEDIDOS__NUEVO = 400
    '------------------------------------------------------------------------------

    ID_BUTTON_COMPRAS__REQUERIMIENTOS__NUEVO = 500
    ID_BUTTON_COMPRAS__REQUERIMIENTOS__LISTADO = 501

    ID_BUTTON_COMPRAS__PETICION_OFERTA__NUEVA = 600
    ID_BUTTON_COMPRAS__PETICION_OFERTA__LISTADO = 601
    ID_BUTTON_COMPRAS__PETICION_OFERTA__COMPRAR = 602

    ID_BUTTON_COMPRAS__ORDEN_COMPRA__NUEVA = 700
    ID_BUTTON_COMPRAS__ORDEN_COMPRA__LISTADO = 701

    ID_BUTTON_COMPRAS__PRECIOS__ADMINISTRAR = 800
    ID_BUTTON_COMPRAS__PRECIOS__HISTORICO = 801

    '------------------------------------------------------------------------------

    ID_BUTTON_PLANEAMIENTO__ORDEN_TRABAJO__NUEVA = 900
    ID_BUTTON_PLANEAMIENTO__ORDEN_TRABAJO__LISTADO = 901
    ID_BUTTON_PLANEAMIENTO__ORDEN_TRABAJO__HISTORICO = 902
    ID_BUTTON_PLANEAMIENTO__ORDEN_TRABAJO__MARCO_NUEVA = 903
    ID_BUTTON_PLANEAMIENTO__ORDEN_TRABAJO__PLANIFICAR = 904

    ID_BUTTON_PLANEAMIENTO__ORDEN_ENTREGA__NUEVA = 1000
    ID_BUTTON_PLANEAMIENTO__ORDEN_ENTREGA__LISTADO = 1001

    ID_BUTTON_PLANEAMIENTO__SEGUIMIENTO__GLOBAL = 1100
    ID_BUTTON_PLANEAMIENTO__SEGUIMIENTO__DE_RUTAS = 1101
    ID_BUTTON_PLANEAMIENTO__SEGUIMIENTO__BARCODE = 1102
    ID_BUTTON_PLANEAMIENTO__SEGUIMIENTO__BARCODE_PROCESOS = 11021
    ID_BUTTON_PLANEAMIENTO__SEGUIMIENTO__BARCODE_RUTAS = 11022
    ID_BUTTON_PLANEAMIENTO__SEGUIMIENTO__BARCODE_INICIO_TAREAS_ASIGNADAS = 11023
    ID_BUTTON_PLANEAMIENTO__SEGUIMIENTO__BARCODE_FIN_TAREAS_ASIGNADAS = 11024

    ID_BUTTON_PLANEAMIENTO__SEGUIMIENTO__VER_TIEMPOS = 1103
    ID_BUTTON_PLANEAMIENTO__SEGUIMIENTO__VER_NNC = 1104
    ID_BUTTON_PLANEAMIENTO__SEGUIMIENTO__OPER_PROCESO = 1105
    ID_BUTTON_PLANEAMIENTO__SEGUIMIENTO__BUSQUEDA_PROGRAMAS = 1106

    ID_BUTTON_PLANEAMIENTO__REMITOS__NUEVO = 1200
    ID_BUTTON_PLANEAMIENTO__REMITOS__REMITAR_CONCEPTO = 1201
    ID_BUTTON_PLANEAMIENTO__REMITOS__LISTADO = 1202

    '------------------------------------------------------------------------------

    ID_BUTTON_DESARROLLO__CENTRO_DE_COSTOS__NUEVO_ELEMENTO = 1300
    ID_BUTTON_DESARROLLO__CENTRO_DE_COSTOS__NUEVO_CONJUNTO = 1301
    ID_BUTTON_DESARROLLO__CENTRO_DE_COSTOS__LISTADO = 1302


    ID_BUTTON_DESARROLLO__MATERIA_PRIMA__NUEVO_MATERIAL = 1400
    ID_BUTTON_DESARROLLO__MATERIA_PRIMA__RUBROS = 1401
    ID_BUTTON_DESARROLLO__MATERIA_PRIMA__GRUPOS = 1402
    ID_BUTTON_DESARROLLO__MATERIA_PRIMA__ALMACENES = 1403
    ID_BUTTON_DESARROLLO__MATERIA_PRIMA__LISTADO = 1404
    ID_BUTTON_DESARROLLO__MATERIA_PRIMA__HISTORIAL = 1405

    ID_BUTTON_DESARROLLO__MANO_DE_OBRA__NUEVA_TAREA = 1500
    ID_BUTTON_DESARROLLO__MANO_DE_OBRA__SECTORES = 1501
    ID_BUTTON_DESARROLLO__MANO_DE_OBRA__TAREAS = 1502
    ID_BUTTON_DESARROLLO__MANO_DE_OBRA__CATEGORIA_SUELDOS = 1503
    ID_BUTTON_DESARROLLO__MANO_DE_OBRA__SUELDO = 1504

    '------------------------------------------------------------------------------

    ID_BUTTON_ADMINISTRACION__FACTURACION__REMITOS = 1600
    
    ID_BUTTON_ADMINISTRACION__FACTURACION__NUEVA_PROFORMA = 1601
    ID_BUTTON_ADMINISTRACION__FACTURACION__CREAR_PROFORMA = 1800
    ID_BUTTON_ADMINISTRACION__FACTURAS_PROFORMA = 1801
    
    
    ID_BUTTON_ADMINISTRACION__FACTURACION__NUEVA = 1601
    ID_BUTTON_ADMINISTRACION__FACTURACION__NUEVA_FC = 1602
    ID_BUTTON_ADMINISTRACION__FACTURACION__NUEVA_ND = 1603
    ID_BUTTON_ADMINISTRACION__FACTURACION__NUEVA_NC = 1604
    ID_BUTTON_ADMINISTRACION__FACTURACION__NUEVA_ANTICIPO = 16040
    ID_BUTTON_ADMINISTRACION__FACTURACION__FACTURAS = 1605

    ID_BUTTON_ADMINISTRACION__COBRANZAS__RECIBOS = 1700
    ID_BUTTON_ADMINISTRACION__COBRANZAS__NUEVO_RECIBO = 1701
    ID_BUTTON_ADMINISTRACION__COBRANZAS__DEUDORES = 1702

    ID_BUTTON_ADMINISTRACION__CTAS_CTES = 600
    ID_BUTTON_ADMINISTRACION__CTAS_CTES__CREAR_RECIBO = 1078
    ID_BUTTON_ADMINISTRACION__CTAS_CTES__VER_RECIBOS = 1079
    ID_BUTTON_ADMINISTRACION__CTAS_CTES__MOVIMIENTOS = 1800
    ID_BUTTON_ADMINISTRACION__CTAS_CTES__SALDOS = 1801

    ID_BUTTON_ADMINISTRACION__COMPRAS__NUEVA = 1900
    ID_BUTTON_ADMINISTRACION__COMPRAS__LISTADO = 1901
    ID_BUTTON_ADMINISTRACION__COMPRAS__PLAN_DE_CUENTAS = 1902
    ID_BUTTON_ADMINISTRACION__COMPRAS__PLAN_DE_CUENTAS_VER = 1903
    ID_BUTTON_ADMINISTRACION__COMPRAS__PLAN_DE_CUENTAS_DEFINIR = 1904
    ID_BUTTON_ADMINISTRACION__COMPRAS__CTA_CTE = 1905
    ID_BUTTON_ADMINISTRACION__COMPRAS__RESUMEN__SALDOS = 1906
    ID_BUTTON_ADMINISTRACION__VARIOS__PADRON_IIBB = 2000
    ID_BUTTON_ADMINISTRACION__VARIOS__CENTRO_CAMBIO = 2001


    ID_BUTTON_ADMINISTRACION__VARIOS__SUBDIARIOS = 2006
    ID_BUTTON_ADMINISTRACION__VARIOS__SUBDIARIOS_VENTAS = 2003
    ID_BUTTON_ADMINISTRACION__VARIOS__SUBDIARIOS_COBRANZAS = 2004
    ID_BUTTON_ADMINISTRACION__VARIOS__SUBDIARIOS_RETENCIONES = 2005

    ID_BUTTON_ADMINISTRACION__VARIOS__SUBDIARIOS_COMPRAS = 20021
    ID_BUTTON_ADMINISTRACION__VARIOS__SUBDIARIOS_IVACOMPRAS = 20031
    ID_BUTTON_ADMINISTRACION__VARIOS__SUBDIARIOS_POSICION_IVA_MENSUAL = 20041


    ID_BUTTON_ADMINISTRACION__VARIOS__INFORMES = 2006
    ID_BUTTON_ADMINISTRACION__VARIOS__INFORMES_CLIENTE = 2007
    ID_BUTTON_ADMINISTRACION__VARIOS__INFORMES_ORDEN_TRABAJO = 2008
    ID_BUTTON_ADMINISTRACION__VARIOS__INFORMES_TOTAL = 2009
    ID_BUTTON_ADMINISTRACION__VARIOS__INFORMES_PERIODO = 2010

    ID_BUTTON_ADMINISTRACION__EXTRAS__REPORTE_CMC = 2202
    ID_BUTTON_ADMINISTRACION__EXTRAS__REPORTE_IVAC = 2013
    ID_BUTTON_ADMINISTRACION__EXTRAS__REPORTE_CAA = 2203
    ID_BUTTON_ADMINISTRACION__EXTRAS__REPORTE_VAA = 2204
    
    ID_BUTTON_ADMINISTRACION__CHEQUES = 2011
    ID_BUTTON_ADMINISTRACION__CHEQUES_DEPOSITAR = 20111

    ID_BUTTON_ADMINISTRACION__COMPRAS__LIQUIDACIONES = 2012
    ID_BUTTON_ADMINISTRACION__CAJABANCOS__CREAR_LIQUIDACION_CAJA = 12011
    ID_BUTTON_ADMINISTRACION__CAJABANCOS__CREAR_LIQUIDACION_CAJA_DG = 12015
    ID_BUTTON_ADMINISTRACION__CAJABANCOS__LISTA_LIQUIDACION_CAJA = 120121
    
    ID_BUTTON_ADMINISTRACION__ORDEN_PAGO = 121
    ID_BUTTON_ADMINISTRACION__CAJABANCOS__CREAR_ORDEN_PAGO = 20121
    ID_BUTTON_ADMINISTRACION__CAJABANCOS__ORDEN_PAGO_LISTA = 20131
    ID_BUTTON_ADMINISTRACION__CAJABANCOS__TRANSFERENCIAS = 20132

    ID_BUTTON_ADMINISTRACION__CAJABANCOS__COMPENSATORIOS = 2014
    ID_BUTTON_ADMINISTRACION__CAJABANCOS__RESUMEN_PAGOS = 2015
    ID_BUTTON_ADMINISTRACION__CAJABANCOS__RESUMEN_COBROS = 20155
    ID_BUTTON_ADMINISTRACION__CAJABANCOS__MOVIMIENTO__FONDOS = 2016
    ID_BUTTON_ADMIN_LIQUIDACIONES_CREAR = 2014
    ID_BUTTON_ADMIN_LIQUIDACIONES_VER = 20151


    '------------------------------------------------------------------------------

    ID_BUTTON_CLIENTES_PROVEEDORES__CLIENTES__NUEVO = 2200
    ID_BUTTON_CLIENTES_PROVEEDORES__CLIENTES__LISTADO = 2213

    ID_BUTTON_CLIENTES_PROVEEDORES__PROVEEDORES__NUEVO = 2210
    ID_BUTTON_CLIENTES_PROVEEDORES__PROVEEDORES__LISTADO = 2211
    ID_BUTTON_CLIENTES_PROVEEDORES__PROVEEDORES__ASOCRUBROS = 2212

    'ID_BUTTON_CLIENTES_PROVEEDORES__AGENDA__NUEVO = 2300
    ID_BUTTON_CLIENTES_PROVEEDORES__AGENDA__VER = 2301

    '------------------------------------------------------------------------------

    ID_BUTTON_USUARIO__HERRAMIENTAS__TABLERO = 2400
    ID_BUTTON_USUARIO__HERRAMIENTAS__AGENDA = 2401
    ID_BUTTON_USUARIO__HERRAMIENTAS__CAMBIAR_CONTRASEÑA = 2402
    ID_BUTTON_USUARIO__HERRAMIENTAS__EVENTOS = 2403
    ID_BUTTON_USUARIO__HERRAMIENTAS___ASIGNACION_EVENTOS = 2404
End Enum
