select count(i.id) as inci, count(a.id) as archi, p.idUsuarioFinalizado,p.fechaFinalizado,p.vencimientoPresupuesto as vencimiento,p.id,p.fecha,p.fechaEntrega,sp.usuario,p.estado,p.detalle,p.descuento, c.razon from presupuestos p inner join clientes c on p.idCliente = c.id inner join usuarios sp on p.idvendedor=sp.id  left join Incidencias i on i.idReferencia=p.id and i.origen=2 left join archivos a on a.idPieza=p.id and a.origen=2 where (p.estado <6 or p.estado=7) group by p.id order by id desc

select count(i.id) as inci, p.idUsuarioFinalizado,p.fechaFinalizado,p.vencimientoPresupuesto as vencimiento,p.id,p.fecha,p.fechaEntrega,sp.usuario,p.estado,p.detalle,p.descuento, c.razon from presupuestos p inner join clientes c on p.idCliente = c.id inner join usuarios sp on p.idvendedor=sp.id  left join Incidencias i on i.idReferencia=p.id and i.origen=2 left join archivos a on a.idpieza=p.id and a.origen=2 where p.idcliente=" & cliente & "  and (p.estado <6 or p.estado=7) group by p.id order by id desc

select count(i.id) as inci, count(a.id) as archi p.idUsuarioFinalizado,p.fechaFinalizado,p.vencimientoPresupuesto as vencimiento,p.id,p.fecha,p.fechaEntrega,sp.usuario,p.estado,p.detalle,p.descuento, c.razon from presupuestos p inner join clientes c on p.idCliente = c.id inner join usuarios sp on p.idvendedor=sp.id  left join Incidencias i on i.idReferencia=p.id and i.origen=2 left join archivos a on a.idpieza=p.id and a.origen=2 where p.idcliente=12  and (p.estado <6 or p.estado=7) group by p.id order by id desc

select count(i.id) as inci, count(a.id) as archi, p.idUsuarioFinalizado,p.fechaFinalizado,p.vencimientoPresupuesto as vencimiento,p.id,p.fecha,p.fechaEntrega,sp.usuario,p.estado,p.detalle,p.descuento, c.razon from presupuestos p inner join clientes c on p.idCliente = c.id inner join usuarios sp on p.idvendedor=sp.id  left join Incidencias i on i.idReferencia=p.id and i.origen=1 left join archivos a on a.idpieza=p.id and a.origen=2 where p.estado=6 group by p.id order by id desc

select count(i.id) as inci, count(a.id) as archi, p.idUsuarioFinalizado,p.fechaFinalizado,p.vencimientoPresupuesto as vencimiento,p.id,p.fecha,p.fechaEntrega,sp.usuario,p.estado,p.detalle,p.descuento, c.razon from presupuestos p inner join clientes c on p.idCliente = c.id inner join usuarios sp on p.idvendedor=sp.id  left join Incidencias i on i.idReferencia=p.id and i.origen=1 left join archivos a on a.idPieza=p.id and a.origen=2 where p.idcliente=" & cliente & "  and p.estado=6 group by p.id order by id desc
